name: Flex Bison CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install apt packages
        run: sudo apt install build-essential flex bison

      - name: Make build
        run: make build

      - uses: actions/upload-artifact@v3
        with:
          name: binary
          path: ./*.bin
          if-no-files-found: error

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: binary

      - name: Fix binary permissions
        run: chmod +x *.bin

      - name: Make test
        run: make test
